import type Database from 'better-sqlite3'
import { DEFAULT_USER_ID, FOCUS_EXP_FORMULA_VERSION } from '../constants'
import { insertExpEvent } from './exp'

export interface FocusSessionRow {
  id: number
  client_event_id: string
  user_id: string
  session_date: string
  planned_duration_minutes: number
  actual_duration_seconds: number
  started_at: string
  completed_at: string
  created_at: string
}

export interface InsertFocusSessionInput {
  /** Stable id generated by the caller so retries are idempotent. */
  clientEventId: string
  /** Local date (YYYY-MM-DD) of completion in the user's timezone. */
  sessionDate: string
  plannedDurationMinutes: number
  actualDurationSeconds: number
  startedAt: string
  completedAt: string
  userId?: string
}

/**
 * Focus EXP: one EXP per completed minute, minimum one
 * (see SCHEMA_PROPOSAL.md "EXP and levels").
 */
export function focusExpAward(actualDurationSeconds: number): number {
  return Math.max(1, Math.floor(actualDurationSeconds / 60))
}

function getFocusSessionByClientEventId(
  db: Database.Database,
  clientEventId: string
): FocusSessionRow | undefined {
  return db.prepare('SELECT * FROM focus_sessions WHERE client_event_id = ?').get(clientEventId) as
    FocusSessionRow | undefined
}

function getFocusSessionById(db: Database.Database, id: number): FocusSessionRow {
  return db.prepare('SELECT * FROM focus_sessions WHERE id = ?').get(id) as FocusSessionRow
}

/**
 * Records a completed focus session and its positive EXP award in one
 * transaction (transaction contract #1). Idempotent: calling again with the
 * same `clientEventId` returns the existing session without a second award.
 */
export function insertFocusSession(
  db: Database.Database,
  input: InsertFocusSessionInput
): FocusSessionRow {
  const userId = input.userId ?? DEFAULT_USER_ID

  const existing = getFocusSessionByClientEventId(db, input.clientEventId)
  if (existing) return existing

  const createSession = db.transaction((): number => {
    const now = new Date().toISOString()
    const info = db
      .prepare(
        `INSERT INTO focus_sessions
           (client_event_id, user_id, session_date, planned_duration_minutes,
            actual_duration_seconds, started_at, completed_at, created_at)
         VALUES
           (@clientEventId, @userId, @sessionDate, @plannedDurationMinutes,
            @actualDurationSeconds, @startedAt, @completedAt, @createdAt)`
      )
      .run({
        clientEventId: input.clientEventId,
        userId,
        sessionDate: input.sessionDate,
        plannedDurationMinutes: input.plannedDurationMinutes,
        actualDurationSeconds: input.actualDurationSeconds,
        startedAt: input.startedAt,
        completedAt: input.completedAt,
        createdAt: now
      })

    const sessionId = Number(info.lastInsertRowid)

    insertExpEvent(db, {
      idempotencyKey: `focus_session:${sessionId}`,
      userId,
      sourceType: 'focus_session',
      sourceId: String(sessionId),
      amount: focusExpAward(input.actualDurationSeconds),
      formulaVersion: FOCUS_EXP_FORMULA_VERSION,
      reason: null,
      createdAt: now
    })

    return sessionId
  })

  return getFocusSessionById(db, createSession())
}

/** Most recently completed sessions first. Read-only (Focus Room, Dashboard). */
export function listRecentFocusSessions(
  db: Database.Database,
  options: { userId?: string; limit?: number } = {}
): FocusSessionRow[] {
  const userId = options.userId ?? DEFAULT_USER_ID
  const limit = options.limit ?? 50
  return db
    .prepare(
      `SELECT * FROM focus_sessions
       WHERE user_id = ?
       ORDER BY completed_at DESC
       LIMIT ?`
    )
    .all(userId, limit) as FocusSessionRow[]
}

/** Sessions whose local `session_date` falls in [startDate, endDate] inclusive. */
export function listFocusSessionsByDateRange(
  db: Database.Database,
  startDate: string,
  endDate: string,
  options: { userId?: string } = {}
): FocusSessionRow[] {
  const userId = options.userId ?? DEFAULT_USER_ID
  return db
    .prepare(
      `SELECT * FROM focus_sessions
       WHERE user_id = ? AND session_date >= ? AND session_date <= ?
       ORDER BY session_date ASC, completed_at ASC`
    )
    .all(userId, startDate, endDate) as FocusSessionRow[]
}

/** Count of focus sessions completed on a specific date in the user's timezone. */
export function countFocusSessionsByDate(
  db: Database.Database,
  sessionDate: string,
  userId: string = DEFAULT_USER_ID
): number {
  const result = db
    .prepare('SELECT COUNT(*) AS count FROM focus_sessions WHERE user_id = ? AND session_date = ?')
    .get(userId, sessionDate) as { count: number }
  return result.count
}

/** Sum of all actual_duration_seconds for sessions on a specific date. */
export function totalFocusMinutesByDate(
  db: Database.Database,
  sessionDate: string,
  userId: string = DEFAULT_USER_ID
): number {
  const result = db
    .prepare(
      `SELECT COALESCE(SUM(actual_duration_seconds), 0) AS total_seconds
       FROM focus_sessions
       WHERE user_id = ? AND session_date = ?`
    )
    .get(userId, sessionDate) as { total_seconds: number }
  return Math.floor(result.total_seconds / 60)
}
