import type Database from 'better-sqlite3'
import { HABIT_COMPLETION_EXP_AMOUNT, HABIT_EXP_FORMULA_VERSION } from '../constants'
import { getHabit, type HabitFrequency } from './habits'
import { insertExpEvent } from './exp'

export interface HabitCompletionRow {
  id: number
  habit_id: string
  period_type: HabitFrequency
  period_start: string
  completed: number
  revision: number
  created_at: string
  updated_at: string
}

export interface HabitCompletionEventRow {
  id: number
  client_event_id: string
  completion_id: number
  revision: number
  completed: number
  occurred_at: string
}

export interface ToggleHabitCompletionInput {
  habitId: string
  /** Local period start (YYYY-MM-DD): the date itself for daily habits, the
   * Monday starting the ISO week for weekly habits. Caller is responsible for
   * aligning weekly periods to Monday. */
  periodStart: string
  /** Stable id generated by the caller so retries are idempotent. */
  clientEventId: string
}

function getHabitCompletion(
  db: Database.Database,
  habitId: string,
  periodStart: string
): HabitCompletionRow | undefined {
  return db
    .prepare('SELECT * FROM habit_completions WHERE habit_id = ? AND period_start = ?')
    .get(habitId, periodStart) as HabitCompletionRow | undefined
}

function getHabitCompletionEventByClientEventId(
  db: Database.Database,
  clientEventId: string
): HabitCompletionEventRow | undefined {
  return db
    .prepare('SELECT * FROM habit_completion_events WHERE client_event_id = ?')
    .get(clientEventId) as HabitCompletionEventRow | undefined
}

function getHabitCompletionById(db: Database.Database, id: number): HabitCompletionRow {
  return db.prepare('SELECT * FROM habit_completions WHERE id = ?').get(id) as HabitCompletionRow
}

/**
 * Toggles one habit period between complete and incomplete: upserts
 * `habit_completions`, appends a `habit_completion_events` audit row, and
 * writes the matching `+10`/`-10` `exp_events` row, all in one transaction
 * (transaction contract #2). Idempotent via `clientEventId`: a retry returns
 * the completion state unchanged with no second toggle or EXP event.
 *
 * Throws if the habit does not exist or if `periodStart`'s implied period type
 * does not match the habit's immutable `frequency` — callers must derive
 * `periodStart` from the habit's own frequency before calling this.
 */
export function toggleHabitCompletion(
  db: Database.Database,
  input: ToggleHabitCompletionInput
): HabitCompletionRow {
  const habit = getHabit(db, input.habitId)
  if (!habit) throw new Error(`Habit not found: ${input.habitId}`)

  const existingEvent = getHabitCompletionEventByClientEventId(db, input.clientEventId)
  if (existingEvent) return getHabitCompletionById(db, existingEvent.completion_id)

  const applyToggle = db.transaction((): number => {
    const now = new Date().toISOString()
    const existingCompletion = getHabitCompletion(db, input.habitId, input.periodStart)

    let completionId: number
    let newCompleted: 0 | 1
    let newRevision: number

    if (!existingCompletion) {
      newCompleted = 1
      newRevision = 1
      const info = db
        .prepare(
          `INSERT INTO habit_completions
             (habit_id, period_type, period_start, completed, revision, created_at, updated_at)
           VALUES
             (@habitId, @periodType, @periodStart, @completed, @revision, @createdAt, @updatedAt)`
        )
        .run({
          habitId: input.habitId,
          periodType: habit.frequency,
          periodStart: input.periodStart,
          completed: newCompleted,
          revision: newRevision,
          createdAt: now,
          updatedAt: now
        })
      completionId = Number(info.lastInsertRowid)
    } else {
      completionId = existingCompletion.id
      newCompleted = existingCompletion.completed === 1 ? 0 : 1
      newRevision = existingCompletion.revision + 1
      db.prepare(
        `UPDATE habit_completions
         SET completed = @completed, revision = @revision, updated_at = @updatedAt
         WHERE id = @id`
      ).run({ id: completionId, completed: newCompleted, revision: newRevision, updatedAt: now })
    }

    const eventInfo = db
      .prepare(
        `INSERT INTO habit_completion_events
           (client_event_id, completion_id, revision, completed, occurred_at)
         VALUES
           (@clientEventId, @completionId, @revision, @completed, @occurredAt)`
      )
      .run({
        clientEventId: input.clientEventId,
        completionId,
        revision: newRevision,
        completed: newCompleted,
        occurredAt: now
      })
    const eventId = Number(eventInfo.lastInsertRowid)

    insertExpEvent(db, {
      idempotencyKey: `habit_completion_event:${eventId}`,
      userId: habit.user_id,
      sourceType: 'habit_completion',
      sourceId: String(eventId),
      amount: newCompleted === 1 ? HABIT_COMPLETION_EXP_AMOUNT : -HABIT_COMPLETION_EXP_AMOUNT,
      formulaVersion: HABIT_EXP_FORMULA_VERSION,
      reason: null,
      createdAt: now
    })

    return completionId
  })

  return getHabitCompletionById(db, applyToggle())
}

/** Completed period_start dates for one habit, ascending — for streak calculations. */
export function listCompletedPeriods(db: Database.Database, habitId: string): string[] {
  const rows = db
    .prepare(
      `SELECT period_start FROM habit_completions
       WHERE habit_id = ? AND completed = 1
       ORDER BY period_start ASC`
    )
    .all(habitId) as { period_start: string }[]
  return rows.map((row) => row.period_start)
}
